version: '3'
services:
  rtl-frontend:
    container_name: RateTheLandlord-FE
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - ${FEPORT}:${FEPORT}
    env_file:
      - .env